title: Your Blog Title
description: A simple minimal blog
author: Noor   # Change to your name
baseurl: ""    # Important for GitHub Pages
url: "https://2025-BSCPE-145.github.io"

# Theme (GitHub Pages supports this by default)
theme: minima

# Optional: Show future posts or not
future: true

# Optional: Add social links (uncomment if you want)
# twitter_username: yourtwitter
# github_username:  2025-BSCPE-145
